### ISSUE TITLE
Create Dino

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-11/dino-kennel#1]
# User Story
As a user, I need to be able to add a new dino.

# AC
**WHEN** the page loads
**THEN** I should see a closed accordion with a link that says 'Add Dino'
**AND** when I click on the link it should open the accordion
**AND** I should see form elements for name, age, type, owner, imageUrl and a submit button
**AND** when I click the submit button it should close the accordion and console the dino array.

# Dev Notes
+ hardcode an accordion in ```index.html``` 
+ create an array in ```main.js``` called ```dinos```
+ hardcode a bootstrap form inside the ```card-body``` class. The form should have 5 fields and a submit button whose id is ```btn-submit```.  Each input should have an id.  Something like `dino-name`
+ attach an ```eventListener``` to the submit button that resets the page and calls a function called ```newDino``` that creates a new dino based on the input ```.value``` of the form fields. The function then outputs the contents of the ```dinos``` array via ```console.log()```
+ create a function called `formCollapse` that adds a class of `collapsed` and updates aria-expanded to false on the collapse.
+ format each ```dino``` using the copypasta in the comments below
+ to get the unique id = `dino${dinos.length +1}`

**Comment by zoeames** [comment]
+ Use bootstrap accordion:  https://getbootstrap.com/docs/4.4/components/collapse/#accordion-example
+ use the form group https://getbootstrap.com/docs/4.3/components/forms/

**Comment by zoeames** [comment]
Sample Dino:
```js
const dinos = [
  {
    id: 'dino1',
    name: 'Rex',
    type: 'T Rex',
    age: 100,
    owner: 'Zoe',
    adventures: [],
    health: 100,
    imageUrl: 'https://images-na.ssl-images-amazon.com/images/I/61fC04pumjL._AC_SL1001_.jpg'
  }
]
```

**Comment by zoeames** [comment]
Accordion wireframe:
![image](https://user-images.githubusercontent.com/8093647/74787859-d2d44780-5275-11ea-9bb0-50515555c30b.png)

**Comment by AaronLain** [comment]
Comment
