### ISSUE TITLE
View GRAVEYARD

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-11/dino-kennel#10]
# User Story
As a user, I would like to see all dinos who are dead in the graveyard.

# AC
**WHEN** a dino has a health score less than 1 
**THEN** they should show up in the graveyard
**AND** they should not appear in the ALL dinos section
**AND** I should not be able to click the feed, adventure, or delete buttons

# Dev Notes
- [x] Create container to hold 💀 dinos
    ```html
    <div id="graveyard"></div>
    ```
- [x] Create `deadDinoDomStringBuilder(dinos)` function
    * Parameter is collection of dinos
    * Create the dino card `domString`
    * Pass `domString` to `printToDom` function, printing to `#graveyard`
- [x] Create `findDeadDinos()` function
    * Create temp `deadDinos` array that uses filter method to get dinos who have `health < 1`
    * At the end pass `deadDinos` array to `deadDinoDomStringBuilder`
- [x] Call  `findDeadDinos()` in `init()` function

**Comment by luketlancaster** [comment]
@zoeames ping for **Dev Notes** review

**Comment by luketlancaster** [comment]
TODO: Need card for `deadDinoDomStringBuilder()`. Guessing it'll be implemented in #2, and most of that could be used for it?

**Comment by zoeames** [comment]
use bootstrap disabled: https://getbootstrap.com/docs/4.4/components/buttons/#disabled-state
