### ISSUE TITLE
Back Button

### ISSUE THREAD

**Issue by westmary48** [nss-evening-cohort-11/dino-kennel#14]
# User Story
As a user, I should be able to go back to the home page after I have viewed a single dino

# Acceptance Criteria
**WHEN** I view a single dino
**THEN** I should see a button on the top of the page
**THAT**  will take me back to the home page
**WHEN** it is clicked

# Dev Notes
- create an x button with id = `close-single-view`
- add event listener by id that calls function named `closeSingleViewEvent`
- closeSingleViewEvent -` printToDom('single-view', '')` and then call `printDinos`

**Comment by zoeames** [comment]
see #3 for all the function words
